# Generated by Django 3.2.8 on 2021-10-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Kişi'},
        ),
    ]
